/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.rpc;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.14.1)", date = "2021-07-04")
public class Package implements org.apache.thrift.TBase<Package, Package._Fields>, java.io.Serializable, Cloneable, Comparable<Package> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Package");

  private static final org.apache.thrift.protocol.TField MESSEGES_FIELD_DESC = new org.apache.thrift.protocol.TField("Messeges", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField LASTINT_FIELD_DESC = new org.apache.thrift.protocol.TField("Lastint", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new PackageStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new PackageTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> Messeges; // required
  public int Lastint; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MESSEGES((short)1, "Messeges"),
    LASTINT((short)2, "Lastint");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MESSEGES
          return MESSEGES;
        case 2: // LASTINT
          return LASTINT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __LASTINT_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MESSEGES, new org.apache.thrift.meta_data.FieldMetaData("Messeges", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.LASTINT, new org.apache.thrift.meta_data.FieldMetaData("Lastint", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Package.class, metaDataMap);
  }

  public Package() {
    this.Messeges = new java.util.ArrayList<java.lang.String>();

    this.Lastint = 1;

  }

  public Package(
    java.util.List<java.lang.String> Messeges,
    int Lastint)
  {
    this();
    this.Messeges = Messeges;
    this.Lastint = Lastint;
    setLastintIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Package(Package other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetMesseges()) {
      java.util.List<java.lang.String> __this__Messeges = new java.util.ArrayList<java.lang.String>(other.Messeges);
      this.Messeges = __this__Messeges;
    }
    this.Lastint = other.Lastint;
  }

  public Package deepCopy() {
    return new Package(this);
  }

  @Override
  public void clear() {
    this.Messeges = new java.util.ArrayList<java.lang.String>();

    this.Lastint = 1;

  }

  public int getMessegesSize() {
    return (this.Messeges == null) ? 0 : this.Messeges.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.lang.String> getMessegesIterator() {
    return (this.Messeges == null) ? null : this.Messeges.iterator();
  }

  public void addToMesseges(java.lang.String elem) {
    if (this.Messeges == null) {
      this.Messeges = new java.util.ArrayList<java.lang.String>();
    }
    this.Messeges.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.lang.String> getMesseges() {
    return this.Messeges;
  }

  public Package setMesseges(@org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> Messeges) {
    this.Messeges = Messeges;
    return this;
  }

  public void unsetMesseges() {
    this.Messeges = null;
  }

  /** Returns true if field Messeges is set (has been assigned a value) and false otherwise */
  public boolean isSetMesseges() {
    return this.Messeges != null;
  }

  public void setMessegesIsSet(boolean value) {
    if (!value) {
      this.Messeges = null;
    }
  }

  public int getLastint() {
    return this.Lastint;
  }

  public Package setLastint(int Lastint) {
    this.Lastint = Lastint;
    setLastintIsSet(true);
    return this;
  }

  public void unsetLastint() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __LASTINT_ISSET_ID);
  }

  /** Returns true if field Lastint is set (has been assigned a value) and false otherwise */
  public boolean isSetLastint() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __LASTINT_ISSET_ID);
  }

  public void setLastintIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __LASTINT_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case MESSEGES:
      if (value == null) {
        unsetMesseges();
      } else {
        setMesseges((java.util.List<java.lang.String>)value);
      }
      break;

    case LASTINT:
      if (value == null) {
        unsetLastint();
      } else {
        setLastint((java.lang.Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case MESSEGES:
      return getMesseges();

    case LASTINT:
      return getLastint();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case MESSEGES:
      return isSetMesseges();
    case LASTINT:
      return isSetLastint();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof Package)
      return this.equals((Package)that);
    return false;
  }

  public boolean equals(Package that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_Messeges = true && this.isSetMesseges();
    boolean that_present_Messeges = true && that.isSetMesseges();
    if (this_present_Messeges || that_present_Messeges) {
      if (!(this_present_Messeges && that_present_Messeges))
        return false;
      if (!this.Messeges.equals(that.Messeges))
        return false;
    }

    boolean this_present_Lastint = true;
    boolean that_present_Lastint = true;
    if (this_present_Lastint || that_present_Lastint) {
      if (!(this_present_Lastint && that_present_Lastint))
        return false;
      if (this.Lastint != that.Lastint)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetMesseges()) ? 131071 : 524287);
    if (isSetMesseges())
      hashCode = hashCode * 8191 + Messeges.hashCode();

    hashCode = hashCode * 8191 + Lastint;

    return hashCode;
  }

  @Override
  public int compareTo(Package other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetMesseges(), other.isSetMesseges());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMesseges()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Messeges, other.Messeges);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetLastint(), other.isSetLastint());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLastint()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Lastint, other.Lastint);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Package(");
    boolean first = true;

    sb.append("Messeges:");
    if (this.Messeges == null) {
      sb.append("null");
    } else {
      sb.append(this.Messeges);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("Lastint:");
    sb.append(this.Lastint);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PackageStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public PackageStandardScheme getScheme() {
      return new PackageStandardScheme();
    }
  }

  private static class PackageStandardScheme extends org.apache.thrift.scheme.StandardScheme<Package> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Package struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MESSEGES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.Messeges = new java.util.ArrayList<java.lang.String>(_list0.size);
                @org.apache.thrift.annotation.Nullable java.lang.String _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = iprot.readString();
                  struct.Messeges.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setMessegesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // LASTINT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.Lastint = iprot.readI32();
              struct.setLastintIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Package struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.Messeges != null) {
        oprot.writeFieldBegin(MESSEGES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.Messeges.size()));
          for (java.lang.String _iter3 : struct.Messeges)
          {
            oprot.writeString(_iter3);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(LASTINT_FIELD_DESC);
      oprot.writeI32(struct.Lastint);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PackageTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public PackageTupleScheme getScheme() {
      return new PackageTupleScheme();
    }
  }

  private static class PackageTupleScheme extends org.apache.thrift.scheme.TupleScheme<Package> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Package struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetMesseges()) {
        optionals.set(0);
      }
      if (struct.isSetLastint()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetMesseges()) {
        {
          oprot.writeI32(struct.Messeges.size());
          for (java.lang.String _iter4 : struct.Messeges)
          {
            oprot.writeString(_iter4);
          }
        }
      }
      if (struct.isSetLastint()) {
        oprot.writeI32(struct.Lastint);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Package struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list5 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRING);
          struct.Messeges = new java.util.ArrayList<java.lang.String>(_list5.size);
          @org.apache.thrift.annotation.Nullable java.lang.String _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = iprot.readString();
            struct.Messeges.add(_elem6);
          }
        }
        struct.setMessegesIsSet(true);
      }
      if (incoming.get(1)) {
        struct.Lastint = iprot.readI32();
        struct.setLastintIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

