default:
  image: node:14

stages:
  - lint
  - test
  - build

frontend:
  stage: lint
  before_script:
    - cd packages/frontend
    - npm install
  script:
    - npm run lint
  cache:
    key: frontend
    paths:
      - packages/frontend/node_modules

backend:
  stage: lint
  before_script:
    - cd packages/backend
    - npm install
  script:
    - npm run lint
  cache:
    key: backend
    paths:
      - packages/backend/node_modules

# test_backend:
#  stage: test
#  before_script:
#    - cd packages/backend
#    - npm install
#  script:
#    - npm run test
#  cache:
#    key: backend
#    paths:
#      - packages/backend/node_modules

frontend_build:
  stage: build
  before_script:
    - cd packages/frontend
    - npm install
  script:
    - npm run build

backend_build:
  stage: build
  before_script:
    - cd packages/backend
    - npm install
  script:
    - npm run build
